/* 
Declare a variable userChoice
Declare a variable opponentChoice

Declare a function for ComputerChoice that takes no parameters.
    This function will randomly choose the  opponentChoice
        Assign a number to the 3 choices: ROCK (1), PAPER (2), SCISSORS (3)
        Choose random number between 1 and 3 inclusive.
        IF number equal to 1
            opponentChoice is set to ROCK
        ELSE IF number equal to 2
            opponentChoice is set to PAPER
        ELSE IF number equal to 3
            opponentChoice is set to SCISSORS
        
        return opponentChoice


Declare a function for playRound that takes two string parameters (computerChoice & userChoice)
    userChoice will be inputted by the user as a parameter
    computerChoice will be randomly generated by passing the computerChoice function as a parameter

IF userChoice is equal to ROCK
    IF computerChoice is equal to ROCK
        TIE
    ELSE IF computerChoice is equal to SCISSORS
        USER WINS
    ELSE IF computerChoice is equal to PAPER
        COMPUTER WINS
ELSE IF userChoice is equal to PAPER
    IF computerChoice is equal to ROCK
        USER WINS
    ELSE IF computerChoice is equal to PAPER
        TIE
    ELSE IF computerChoice is equal to SCISSORS
        COMPUTER WINS
ELSE IF userChoice is equal to SCISSORS
    IF computerChoice is equal to ROCK
        COMPUTER WINS
    ELSE IF computerChoice is equal to PAPER
        USER WINS
    ELSE IF computerChoice is equal to SCISSORS
        TIE
ELSE
    Tell user to input a valid choice


CREATE A FUNCTION game() - to play 5 rounds of Rock, Paper, Scissors
    Declare variable computerSelection
    Declare variable playerSelection

    computerScore is equal to ZERO
    playerScore is equal to ZERO

    Play 5 rounds of Rock, Paper, Scissors
        Loop through the following sequence 5 TIMES
            Set computerSelection to computerChoice() function
            Prompt user for their selection
            Set prompt to playerSelection

            Call function playRound() to:
                Say winner of the round
                Add 1 to the score of the winner, none if a tie.
            Show/Print the current score for each player.
        
        After the 5th Game:
            Determine the winner
                IF playerScore is greater than computerScore - player wins!
                ELSE IF computerScore is greater than playerScore - computer wins!
                ELSE its a TIE, everyone wins.



*/

let userChoice;
let opponentChoice;
let playerScore;
let computerScore;

function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.ceil(max);

    return Math.floor(Math.random() * (max - min + 1) + min);
}

function computerChoice() {

    let randomInt = getRandomInt(1, 3);

    if (randomInt == 1) {
        opponentChoice = "rock";
    }
    else if (randomInt == 2) {
        opponentChoice = "paper";
    }
    else if (randomInt == 3) {
        opponentChoice = "scissors";
    }

    return opponentChoice;
}

function playRound(computerSelection, playerSelection) {
    userChoice = playerSelection.toLowerCase();

    if (userChoice == "rock") {
        if (computerSelection == "rock") {
            console.log("It\'s a tie");
        }
        else if (computerSelection == "paper") {
            console.log("You lose! Paper beats rock.");
            computerScore++;
        }
        else if (computerSelection == "scissors") {
            console.log("You win! Rock beats scissors.");
            playerScore++;
        }
    }
    else if (userChoice == "paper") {
        if (computerSelection == "rock") {
            console.log("You win! Paper beats rock.");
            playerScore++;
        }
        else if (computerSelection == "paper") {
            console.log("It\'s a tie.");

        }
        else if (computerSelection == "scissors") {
            console.log("You lose! Scissors beats paper.");
            computerScore++;
        }
    }
    else if (userChoice == "scissors") {
        if (computerSelection == "rock") {
            console.log("You lose! Rock beats scissors.");
            computerScore++;
        }
        else if (computerSelection == "paper") {
            console.log("You win! Scissors beats paper.");
            playerScore++;
        }
        else if (computerSelection == "scissors") {
            console.log("It\'s a tie.");
        }
        else {
            console.log("Please enter a Rock, Paper or Scissors. You've lost this round.");
        }
    }
}

function game() {
    let computerSelection;
    let playerSelection;

    computerScore = 0;
    playerScore = 0;

    for (let i = 0; i < 5; i++) {
        computerSelection = computerChoice();
        let raw = prompt("Choose your fighter! (Rock, Paper, or Scissors)");
        playerSelection = raw.toLowerCase();

        playRound(computerSelection, playerSelection);
        console.log(`Computer Score: ${computerScore}`);
        console.log(`Player Score: ${playerScore}`);
        
    }

    if (computerScore > playerScore) {
        console.log("Computer is the winner! Well played robot.");
    }
    else if (playerScore > computerScore) {
        console.log("Player is the winner! Well done human.");
    }
    else {
        console.log("It\'s a tie! Humans and Robots are equals.");
    }
}